# Generated by Django 2.0.2 on 2018-04-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
    ]
