# Generated by Django 2.0.2 on 2018-04-25 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0006_auto_20180419_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_sent',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of Message Sent'),
            preserve_default=False,
        ),
    ]
