# Generated by Django 2.0.2 on 2018-04-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0007_message_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(help_text='Date of Message Sent'),
        ),
    ]
