# Generated by Django 2.0.2 on 2018-04-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0008_auto_20180424_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='instance_pic',
            field=models.ImageField(blank=True, upload_to='book_image'),
        ),
    ]
