# Generated by Django 2.0.2 on 2018-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0008_auto_20180424_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='instance_pic',
            field=models.TextField(default='https://i.imgur.com/0l2uZR9.jpg'),
        ),
    ]
