# Generated by Django 2.0.2 on 2018-05-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0009_auto_20180501_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(blank=True, default='None', help_text='Message', max_length=1000),
        ),
    ]
