# Generated by Django 2.0.2 on 2018-03-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, choices=[('f', 'Fiction'), ('n', 'Non-Fiction'), ('t', 'Textbook'), ('h', 'History'), ('m', 'Mystery'), ('h', 'History'), ('s', 'Sci-Fi')], default='Fiction', help_text='Select a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200),
        ),
    ]
