# Generated by Django 2.0.2 on 2018-04-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0003_auto_20180413_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='books_offered',
        ),
    ]
