# Generated by Django 2.0.2 on 2018-03-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0006_user_books_wanted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books_offered',
            field=models.ManyToManyField(help_text='THIS IS INCORRECT', to='BookSwap.BookInstance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='books_wanted',
            field=models.ManyToManyField(help_text='THIS IS INCORRECT', to='BookSwap.Book'),
        ),
    ]
