# Generated by Django 2.0.2 on 2018-03-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0011_auto_20180325_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='owner',
        ),
    ]
