# Generated by Django 2.0.2 on 2018-03-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0012_remove_bookinstance_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books_wanted',
            field=models.ManyToManyField(to='BookSwap.Book'),
        ),
    ]
