# Generated by Django 2.0.2 on 2018-03-27 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0013_auto_20180327_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookSwap.User'),
        ),
    ]
