# Generated by Django 2.0.2 on 2018-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0017_auto_20180327_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pic',
            field=models.ImageField(default='book_imgs/default_book.jpg', upload_to='book_imgs/'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='instance_pic',
            field=models.ImageField(default='bookinstance_imgs/default_instance.jpg', upload_to='bookinstance_imgs/'),
        ),
    ]
