# Generated by Django 2.0.2 on 2018-04-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0020_auto_20180413_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='instance_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='books_offered',
        ),
    ]
