# Generated by Django 2.0.2 on 2018-03-25 20:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BookSwap', '0002_auto_20180325_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular user', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter your first name.', max_length=200)),
                ('last_name', models.CharField(help_text='Enter your last name.', max_length=200)),
                ('university', models.CharField(help_text='Enter your school or university.', max_length=200)),
                ('bio', models.CharField(help_text='Enter a short bio.', max_length=200)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='comments',
            field=models.CharField(default='', help_text='Any additional comments about your book (e.g. pricing, reason for getting rid of it, etc).', max_length=500),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book_condition',
            field=models.CharField(blank=True, choices=[('5', 'Like-New'), ('4', 'Good'), ('3', 'Average'), ('2', 'Bad'), ('1', 'Barely Readable')], default='5', help_text='Book condition', max_length=1),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookSwap.User'),
        ),
    ]
